version: "3.8"

services:
  wagtail:
    ports:
      - 8000:8000
    links:
      - db
    volumes:
      - ./app:/app
  db:
    image: postgres:13.1-alpine
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: wagtail-dev
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
      - ./postgres/init:/docker-entrypoint-initdb.d
